/* Do not edit this file.. It will get overwritten by the build script */
if(typeof(bdl) == 'undefined') { bdl = {} };
if(typeof(bdl.geodash) == 'undefined') { bdl.geodash = {} };
bdl.geodash.versions={geodash:"vDEVELOPMENT-1-gbe5a3c3",geodash_ui:"vDEVELOPMENT_ui-0-gbdf3fa4"};
